### ISSUE TITLE
Miss if blobs in MySql

### ISSUE THREAD

**Issue by wattfarnas97** [paulcwarren/spring-content#289] opened 2020-07-22 19:16 UTC
hello . I have a problem with spring content and Mysql. I manage to save my images without any problems.But an hour later the images disappear. The `getContent` returns null.I don’t know if the problem is my database or if it’s in the code.

**Comment by paulcwarren** [comment] 2020-07-23 06:47
Hi @wattfarnas97 

I tested this with our [spring-docs](https://github.com/paulcwarren/spring-docs) example application configured to run against mysql.  Created a bunch of documents and let it sit for a few hours.  Content was all still there.    

Do you have any spring content database initialization configuration?  Because the only thing I can possibly think of that might be causing content deletion (from a spring content perspective) is a situation where your application is restarted AND you have database initialization configured to drop/create the blob table similar to how we sometimes do this in our [examples](https://github.com/paulcwarren/spring-content-examples/blob/e1e6bf47e843f10ad1bb4b6fc549c8539468e3ac/spring-eg-content-jpa/src/test/java/examples/H2TestConfig.java#L64).  Maybe you copied them without fully realizing what they would do?  It's a stretch, I know, but trying to help you out here?

Failing that if you can create a small project that reproduces the issue I can probably track it down that way.

**Comment by wattfarnas97** [comment] 2020-07-23 10:08
Hi.For example yesterday I added pictures night and this morning the pictures disappeared. I use the parameters 
 ```
spring.jpa.show-sql= true 
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
```
.I will try to create the same project type with the same mysql server.Maybe it’s my sgbd that has a problem.

**Comment by wattfarnas97** [comment] 2020-07-23 14:25
you were right.When I restarted  my application I lose all the files  . How to solve this problem. I already use `spring.jpa.hibernate.ddl-auto = update `in my application.properties ,

**Comment by paulcwarren** [comment] 2020-07-24 03:49
Hey @wattfarnas97 ,

Thanks for project.  I took a look.  I thought you were using the jpa storage module so we were looking in the wrong place!  You are actually using the spring-content-fs storage module and relying on spring boot auto-configuration to configure it for you.  This will set a root for content storage under $TMPDIR somewhere.  You get an indication in the logs with this log when you app starts up:

```
Defaulting filesystem root to /var/folders/65/d8zxcwh13sjfrkry92vgs5x80000gr/T/1740157197106430167
```

As a result, every time you app restarts your app you get a new root for content storage so it looks like your content is being deleted but actually the app is just looking in the wrong place.  

You should configure a stable root for your content storage as explained in the docs [here](https://paulcwarren.github.io/spring-content/refs/release/1.1.0.M2/fs-index.html#_annotation_based_configuration).  The easiest way is to configure the property `spring.content.fs.filesystemRoot` in your application.properties.

Anyway, I [pushed a PR](https://github.com/wattfarnas97/mysqlBugTrack/pull/1) for you to take a look at.  Note, I configured spring data/content rest to give me a REST API for demo purposes, the only real change is the change to application.properties.

**Comment by wattfarnas97** [comment] 2020-07-24 08:08
Hello.Finally the mistake came from me . I had not read the documentation well .Thanks you very much.

**Comment by paulcwarren** [comment] 2020-07-24 16:46
No problem.  The docs arent particularly good.  Glad you got it working.  I am going to close this then.

**Closed by paulcwarren** 2020-07-24 16:46 UTC
