### ISSUE TITLE
spring-content S3 doesn't allow path-based bucket access

### ISSUE THREAD

**Issue by kenandalley-gm** [paulcwarren/spring-content#6] opened 2017-05-10 14:56 UTC
Paul,
Based on our email conversation, I'm adding an issue here in regards to the fact that the current spring-content codebase doesn't allow path-based bucket access.  It only allows access like "<bucket>.<hostname>/<resource-location>" and not "<hostname>/<bucket>/<resource-location>".  The cause that you mentioned is the fact that the implementation of "EnableS3Stores" and "EnableS3ContentRepositories" performs an @Import of the "ContextResourceLoaderConfiguration".

After implementing the "S3ClientOptions.setPathStyleAccess(true)" in the @Configuration file, as mentioned in the email, it got farther, but ran into an issue around the AmazonS3Client @Bean.  I got this error:

`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contentEntityRestController' defined in URL [jar:file:/C:/Users/rzcp0f/.m2/repository/com/github/paulcwarren/spring-content-rest/0.0.4-SNAPSHOT/spring-content-rest-0.0.4-SNAPSHOT.jar!/internal/org/springframework/content/rest/controllers/ContentEntityRestController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contentStoreService': Unsatisfied dependency expressed through method 'setFactories' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sopDocumentContentStore': Unsatisfied dependency expressed through field 'client'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.amazonaws.services.s3.AmazonS3' available: expected single matching bean but found 2: getAmazonS3Client,amazonS3`

Based on that error, I had to add @Primary to the AmazonS3Client @Bean in my @Configuration file.  Once I did that, it is now communicating with our internal S3 repository and storing data.  (sorry about the poor formatting - I'm not familiar enough with the markup to get it working)

My Example @Configuration file now:

@Configuration
@ComponentScan
@EnableJpaRepositories
@EnableS3ContentRepositories
public class ApplicationConfig extends AbstractS3StoreConfiguration {

    @Value("${spring.content.s3.url:#{environment.AWS_URL}}")
    private String url;

    @Value("${spring.content.s3.accessKey:#{environment.AWS_ACCESS_KEY}}")
    private String accessKey;

    @Value("${spring.content.s3.secretKey:#{environment.AWS_SECRET_KEY}}")
    private String secretKey;

    @Value("${spring.content.s3.bucket:#{environment.AWS_BUCKET}}")
    private String bucket;

    @Override
    public SimpleStorageResourceLoader simpleStorageResourceLoader() {
        return new SimpleStorageResourceLoader(getAmazonS3Client(getBasicAWSCredentials()));
    }

    @Bean
    public BasicAWSCredentials getBasicAWSCredentials() {
        return new BasicAWSCredentials(accessKey, secretKey);
    }

    @Bean
    S3ClientOptions getS3ClientOptions() {
        S3ClientOptions opts = new S3ClientOptions();
        opts.setPathStyleAccess(true);
        return opts;
    }

    @Bean @Primary
    public AmazonS3Client getAmazonS3Client(AWSCredentials awsCredentials) {
        AmazonS3Client amazonS3Client = new AmazonS3Client(awsCredentials);
        amazonS3Client.setEndpoint(url);
        amazonS3Client.setS3ClientOptions(getS3ClientOptions());
        return amazonS3Client;
    }
}

**Comment by paulcwarren** [comment] 2017-05-18 16:58
Hi Kenan,

I ran into similar issues as I was TDDing the solution for this.  I believe they were due to the `@EnableS3Stores` annotation `@import`ing `ContextResourceLoaderConfiguration`.  

Now, if you had removed that in your code and you were still getting this duplicate bean issue then we will have to investigate further.  

I have pushed the [fix for this](https://github.com/paulcwarren/spring-content/commit/ec59600e9a510d8397911ac7586ff995c822b7df).   So, you might want to pull the latest code and give this another go.  If it is still an issue then let me know and we'll investigate further.

**Comment by paulcwarren** [comment] 2017-07-06 04:59
Hi Kenan,

Just checking back in to see whether this fixed your issue, or not?

**Comment by kenandalley-gm** [comment] 2017-07-06 15:03
I started looking back at this yesterday afternoon and started running into a problem that wouldn't allow me to validate that this issue is fixed.  Re-running the codebase that I have results in a 404 Not Found error due to the fact that either my Repository is not being found or my Entity isn't being found during the PUT request.  Within the ContentEntityRestController.handleMultipart() method, when it tries to "this.getDomainObject()" (2nd line), the AbstractContentPropertyController throws a ResourceNotFoundException.  This is new and not something that I ran into before.  Then, when I tried upgrading to v0.0.5 and run the exact same codebase (only difference is pointing to v0.0.5), I'm getting an error of: "HttpMessageNotReadableException: No suitable HttpMessageConverter found to read request body into object of type class gettingstarted.springcontents3.SopDocument from request with content type of multipart/form-data".

I'm attaching my project files.

[springcontenttest.zip](https://github.com/paulcwarren/spring-content/files/1128250/springcontenttest.zip)

**Comment by paulcwarren** [comment] 2017-07-06 18:07
Thanks Kenan.  I investigated your application and I have found a couple of issues.

1. In 0.0.5-SNAPSHOT our REST layer has undergone a bit of a transformation to make it work more like the Spring Data REST layer.  To that end if you do not specify a 'path' in your `@ContentStoreRestResource` then by default it will export the endpoints to a pluralized version of the domain object - in your case /sopdocuments.  Same as Spring Data would.  So you can either change `files.js` to PUT content to /sopdocuments, or make `@ContentStoreRestResource(path='s3files')` whichever you want.

2. After fixing this I then discovered that the `idConverter` you register is actually being used by the webmvc controller argument resolver which is definitely unexpected/unintended system behavior.   I started a conversation with the Spring guys to figure out what the right fix for this is and I'll create an issue here to track this fix.  Given that in a Spring Boot application ALL converters get added to the webmvc conversion service, we should either be using a stronger typing; e.g. `Converter<String,ContentId>`, or we shouldn't be using the Converter interface at all (which ironically we weren't doing originally).  Once I hear back from them we can fix this immediately for you.  

A couple of additional points.  

- You are using spring content s3 and spring content fs.  I think this is a valid use case (especially for migration use cases) but it isn't something that we claim we currently support.  In my tests it wasnt causing any ill effect so perhaps it just works but if you don't need it then I would recommend removing the spring content fs dependency just in case - or let us know that you need it and we can prioritize this feature.  

- Also I saw that in your domain model `SopDocument` you are re-using the same field for both the Spring Data `@Id` and the Spring Content `@ContentId`.  I actually really like this approach.  We had overlooked it.  It seems to work though but we don't have any tests to prove it so I will add a story to cover us in this regard.  Thanks for suggesting this improvement.  

HTH
_Paul

**Comment by kenandalley-gm** [comment] 2017-07-06 19:07
Paul,
In regards to the 2 different projects "fs" and "s3".  They're both test projects in the same workspace, but do not really overlap.  I started with testing the "fs" project and then added the "s3" project afterwards.  I changed the "files.js" so that it uses the "s3" project instead of the "fs" project for my testing.  So while it's probably a valid use case, especially migration, I wouldn't base that on my project.  :)

I did get the PUT working by adding the "s3files" to the @ContentStoreRestResource.  It does seem a little strange that GET/POST aren't driven by this but use the @RepositoryRestResource instead.  I would think that they'd all be driven by the same resource, but that may just be my ignorance with Spring Data.

So I can confirm that the original bug is partially fixed.  I commented out the S3ClientOptions @Bean (as sent in the zip) and the file was stored into the ECS repository.  However, when I clicked on the filename link to GET the file, the application is throwing a 500 Internal Server Error due to a 403 Forbidden result from ECS.  In the DefaultS3StoreImpl.getContent() method, the "location" gets "absolutify"d to "s3;//<accessKey>/<objectId>" which is not exposed by our ECS repository.

**Comment by paulcwarren** [comment] 2017-07-17 15:38
Hi Kenan,

I did get the PUT working by adding the "s3files" to the @contentstorerestresource. It does seem a little strange that GET/POST aren't driven by this but use the @repositoryrestresource instead. I would think that they'd all be driven by the same resource, but that may just be my ignorance with Spring Data.
[Paul] There are two different Spring projects here; Spring Data REST and Spring Content REST.  They can be used together or not - just like all Spring projects.  They can be used on their on or combined with other Spring projects.  So in this case Spring Data REST exports your "repositories" handling the database access and its endpoints support GET, PUT, POST and DELETE mapping onto SELECT, INSERT, UPDATE and DELETE.  Spring Content REST exports your "stores" handling your file access and its endpoints also actually support GET, PUT, POST and DELETE mapping onto file get, create, update and delete operations.  So actually both sets of endoints handle the same HTTP methods actually.  Spring Data REST handles json requests, Spring Content handles all content related requests; i.e. text/*, application/*, video/* etc.  

So I can confirm that the original bug is partially fixed. I commented out the S3ClientOptions @bean (as sent in the zip) and the file was stored into the ECS repository. However, when I clicked on the filename link to GET the file, the application is throwing a 500 Internal Server Error due to a 403 Forbidden result from ECS. In the DefaultS3StoreImpl.getContent() method, the "location" gets "absolutify"d to "s3;///" which is not exposed by our ECS repository.
[Paul] So we chased this down in the end to an out-of-date aws s3 JAR.  Once we updated spring-content-s3 to pull in aws sdk 1.11 everything was fine including content fetching.  These changes made it into 0.0.5 BTW.  I'll attach an updated zip showing that working (against the last 0.0.5-SNAPSHOT before we made the release).

HTH
_Paul

**Comment by paulcwarren** [comment] 2017-09-06 04:20
Hi Kenan,

Just checking back in on this.  Have you had an opportunity to re test your ECS access.  Just want to make sure we have you covered.

**Comment by kenandalley-gm** [comment] 2017-09-06 14:29
Paul,

I really haven’t had a chance to get back to this.  I probably won’t have a chance to get to this for a while.  I think we’re ok for now, though.  I’ll let you know if I run into anything else.

Kenan Dalley
Development Lead / Quality
GM Phoenix Innovation Center
Office: (602) 566-6762
Cell:   (480) 738-7433
kenan.dalley@gm.com<mailto:kenan.dalley@gm.com>
[GM1 Small]

**Closed** 2017-09-12 16:05 UTC
