### ISSUE TITLE
LockingAndVersioningRepository's delete method clash with CrudRepository'delete method

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#84] opened 2019-10-15 11:26 UTC
I use kotlin defined an interface as follow:

`@RepositoryRestResource(path = "documents", collectionResourceRel = "documents")
interface DocumentRepository : JpaRepository<Document, String>, LockingAndVersioningRepository<Document, String>`

but the compiler compilation fails :
`Inherited platform declarations clash: The following declarations have the same JVM signature (delete(Ljava/lang/Object;)V)
    fun <S : Document!> delete(p0: S!): Unit defined in com.lubansoft.archives.document.DocumentRepository
    fun delete(p0: Document): Unit defined in com.lubansoft.archives.document.DocumentRepository
`

**Comment by paulcwarren** [comment] 2019-10-18 00:09
I am not a Kotlin guy and haven't had an opportunity to try it yet.  Although, I note it increasing popularity and buzz (at SpringOne this year).  But all this means that I might need a bit of help with this one.  Is it possible that you can provide a sample application that exhibits the problem?

**Comment by schocco** [comment] 2020-04-09 05:15
both, `CrudRepository` and `LockingAndVersioningRepository` define a delete() method.
The accepted type is `<S extends T>` in the versioningRepo but just T in the CrudRepo - this might cause the clash.

@lmtoo As a workaround you can override the delete method in your interface like this:

```kotlin
interface DocumentRepository : CrudRepository<Document, UUID>, LockingAndVersioningRepository<Document, UUID> {

    override fun delete(document: Document) {
    }

}
```

**Comment by paulcwarren** [comment] 2020-04-10 00:22
Thanks for the info @schocco that is helpful.  I can certainly take a look at changing that return type for you both.

**Comment by paulcwarren** [comment] 2020-04-10 19:46
Hi @lmtoo @schocco - [this commit](https://github.com/paulcwarren/spring-content/commit/9ede549348b90dd760936c00cc183b61fbdb068c) changes the signature of the `delete` method on the `LockingAndVersioningRepository` to match that of the `CrudRepository`.  Its available from snapshot repository:

```
		<repository>
			<id>snapshots</id>
			<name>nexus</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
``` 

Would one of you mind verifying if this fixes the issue, or not.

Many thanks.

**Comment by paulcwarren** [comment] 2020-04-21 06:00
I think we have resolved this so I am going to close it.  Please feel free to re-open if you find otherwise.

**Closed by paulcwarren** 2020-04-21 06:00 UTC
Labels: help wanted

**Comment by schocco** [comment] 2020-04-22 15:08
> 
> Would one of you mind verifying if this fixes the issue, or not.
> 
> Many thanks.

I just tested with 1.0.0.M10 and can confirm that the issue is solved.

**Comment by paulcwarren** [comment] 2020-04-22 20:13
Thanks @schocco.  The confirmation is very much appreciated.
