### ISSUE TITLE
spring-versions-jpa-boot-starter must add additional config 

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#82] opened 2019-10-12 11:21 UTC
when depedencies spring-versions-jpa-boot-starter and spring-boot-starter-data-jpa ,
SpringBoot application must also add `@EnableJpaRepositories(basePackages = ["com.example.springcontentdemo", "org.springframework.versions"])` , the package `org.springframework.versions`  shuld be auto include.
otherwise JpaAutoConfiguration try to generate method in  LockingAndVersioningRepository ,not to delegate to LockingAndVersioningRepositoryImpl

**Comment by paulcwarren** [comment] 2019-10-18 00:01
It is definitely correct that `org.springframework.versions` has to be in the set of base packages scanned by the spring-data in order to find the implementation class for LockingAndVersioningRepositoryImpl.  This is by design by the spring data folks.  We discussed this with the Spring Data team a little bit in [this issue](https://jira.spring.io/browse/DATACMNS-1487).

But, point taken on the auto-include we can see what we can do here.  I am not sure how much we can influence this.

**Comment by paulcwarren** [comment] 2020-01-25 22:15
Fixed by this [commit](https://github.com/paulcwarren/spring-content/commit/65e0d15d76fcc95d3b6249a37f5106ca1bf1b8b2) in this [build](https://travis-ci.org/paulcwarren/spring-content/builds/641833808).  

Available in the lastest 1.0.0.M6-SNAPSHOT.

**Closed by paulcwarren** 2020-01-25 22:15 UTC
Labels: bug, in-progress
